document.querySelector("#log").addEventListener("click",function(){
    document.querySelector("div.popup").classList.add("active");
});
document.querySelector("#close-btn").addEventListener("click",function(){
    document.querySelector("div.popup").classList.remove("active");
});
document.querySelector("#creare_cont").addEventListener("click",function(){
    document.querySelector("div.popup1").classList.add("active1");
});
document.querySelector("#close-btn1").addEventListener("click",function(){
    document.querySelector("div.popup1").classList.remove("active1");
});